/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.siminimart.form;

import admin.siminimart.main.MainPemesanan;
import admin.siminimart.swing.connectionmysql;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Ahmad Bagus Mas'udi
 */
public class FormPemesanan extends javax.swing.JPanel {
    
    public static String Kode;
    public static String Nama;
    public static String Status;
    public static int TotalHarga;
 
    
    public FormPemesanan() {
        initComponents();
        tampilkanPemesanan();
        lebarKolom();
    }

    public void tampilkanPemesanan() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID Transaksi");
        table.addColumn("Nama");
        table.addColumn("KdBarang");
        table.addColumn("Nama Barang");
        table.addColumn("Jumlah");
        table.addColumn("Total Harga");
        table.addColumn("Tanggal");
        table.addColumn("Status");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                });
            }
            tabelPemesanan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    public void tampilkanSaldo() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("Saldo");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select Saldo from saldo where Nama = '"+ Nama +"'";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1)
                });
            }
            tabelSaldo.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    public void lebarKolom(){
        TableColumn column;
        tabelPemesanan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabelPemesanan.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = tabelPemesanan.getColumnModel().getColumn(1);
        column.setPreferredWidth(120);
        column = tabelPemesanan.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
        column = tabelPemesanan.getColumnModel().getColumn(3);
        column.setPreferredWidth(200);
        column = tabelPemesanan.getColumnModel().getColumn(4);
        column.setPreferredWidth(80);
        column = tabelPemesanan.getColumnModel().getColumn(5);
        column.setPreferredWidth(100);
        column = tabelPemesanan.getColumnModel().getColumn(6);
        column.setPreferredWidth(100);
        column = tabelPemesanan.getColumnModel().getColumn(7);
        column.setPreferredWidth(98);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelSaldo = new javax.swing.JTable();
        panelBorder1 = new admin.siminimart.swing.PanelBorder();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPemesanan = new admin.siminimart.swing.Table();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        panelBorder2 = new admin.siminimart.swing.PanelBorder();
        jLabel4 = new javax.swing.JLabel();
        searchText1 = new admin.siminimart.swing.SearchText();

        tabelSaldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        setBackground(new java.awt.Color(242, 242, 242));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/siminimart/image/trash-can (1).png"))); // NOI18N
        jButton1.setText(" Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/siminimart/image/che2ck.png"))); // NOI18N
        jButton2.setText(" Sudah Diambil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPemesanan);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Pemesanan");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("ID Transaksi");

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/siminimart/image/search.png"))); // NOI18N

        searchText1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchText1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchText1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchText1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemesananMouseClicked
        
        int baris = tabelPemesanan.rowAtPoint(evt.getPoint());
        
        String kode = tabelPemesanan.getValueAt(baris, 0).toString();
        txtID.setText(kode);
        Kode = kode;
        
        String nama = tabelPemesanan.getValueAt(baris, 1).toString().trim();
        Nama = nama;
        
        String totalharga = tabelPemesanan.getValueAt(baris, 5).toString();
        TotalHarga = Integer.parseInt(totalharga);
        
        String status = tabelPemesanan.getValueAt(baris, 6).toString().trim();
        Status = status;
       
        
      
    }//GEN-LAST:event_tabelPemesananMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tampilkanSaldo();
        String saldo = tabelSaldo.getValueAt(0, 0).toString();
        int sld = (Integer.parseInt(saldo) + TotalHarga);
        try {
            Connection con = connectionmysql.koneksiDB();
            String sql1 = "UPDATE saldo set Saldo = "+ sld + " WHERE Nama = '" + Nama + "'";
            Statement S1 = con.createStatement();
            S1.execute(sql1);
            String sql = "DELETE FROM transaksi WHERE id_transaksi = '" + Kode + "'";
            Statement S = con.createStatement();
            S.execute(sql);
            JOptionPane.showMessageDialog(null, "Hapus berhasil");
            new MainPemesanan().setVisible(false);
            new MainPemesanan().setVisible(true);
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(this, "Hapus gagal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
                try {
                    Connection con = connectionmysql.koneksiDB();
                    String sql = "update transaksi set status = 'Sudah Diambil' where id_transaksi = '"+ Kode +"'";
                    Statement S = con.createStatement();
                    S.execute(sql);
                    new MainPemesanan().setVisible(true);
                } catch (Exception e) {
                    System.out.println(e);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchText1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText1KeyReleased
        String cari = searchText1.getText();

        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID Transaksi");
        table.addColumn("Nama");
        table.addColumn("KdBarang");
        table.addColumn("Nama Barang");
        table.addColumn("Jumlah");
        table.addColumn("Total Harga");
        table.addColumn("Tanggal");
        table.addColumn("Status");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi where id_transaksi LIKE '%" + cari+ "%' OR nama LIKE '%" + cari+ "%'";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                });
            }
            tabelPemesanan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
        lebarKolom();
    }//GEN-LAST:event_searchText1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private admin.siminimart.swing.PanelBorder panelBorder1;
    private admin.siminimart.swing.PanelBorder panelBorder2;
    private admin.siminimart.swing.SearchText searchText1;
    private admin.siminimart.swing.Table tabelPemesanan;
    private javax.swing.JTable tabelSaldo;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
