/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.siminimart.form;

import admin.siminimart.main.MainLaporan;
import admin.siminimart.main.MainPemesanan;
import admin.siminimart.swing.connectionmysql;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ahmad Bagus Mas'udi
 */
public class FormLaporan extends javax.swing.JPanel {
    
    public static String Kode;
    public static String Nama;
    public static String Status;
    public static int TotalHarga;
 
    
    public FormLaporan() {
        initComponents();
        tampilkanPemesanan();
        lebarKolom();
    }

    public void tampilkanPemesanan() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID Transaksi");
        table.addColumn("Nama");
        table.addColumn("KdBarang");
        table.addColumn("Nama Barang");
        table.addColumn("Jumlah");
        table.addColumn("Total Harga");
        table.addColumn("Tanggal");
        table.addColumn("Status");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                });
            }
            tabelPemesanan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    
    
    public void lebarKolom(){
        TableColumn column;
        tabelPemesanan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabelPemesanan.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = tabelPemesanan.getColumnModel().getColumn(1);
        column.setPreferredWidth(120);
        column = tabelPemesanan.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
        column = tabelPemesanan.getColumnModel().getColumn(3);
        column.setPreferredWidth(200);
        column = tabelPemesanan.getColumnModel().getColumn(4);
        column.setPreferredWidth(80);
        column = tabelPemesanan.getColumnModel().getColumn(5);
        column.setPreferredWidth(100);
        column = tabelPemesanan.getColumnModel().getColumn(6);
        column.setPreferredWidth(100);
        column = tabelPemesanan.getColumnModel().getColumn(7);
        column.setPreferredWidth(98);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new admin.siminimart.swing.PanelBorder();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPemesanan = new admin.siminimart.swing.Table();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbmBulan = new javax.swing.JComboBox<>();
        panelBorder2 = new admin.siminimart.swing.PanelBorder();
        jLabel4 = new javax.swing.JLabel();
        searchText1 = new admin.siminimart.swing.SearchText();

        setBackground(new java.awt.Color(242, 242, 242));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/siminimart/image/reload.png"))); // NOI18N
        jButton4.setText(" Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/siminimart/image/print.png"))); // NOI18N
        jButton3.setText(" Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/siminimart/image/reload.png"))); // NOI18N
        jButton2.setText(" Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabelPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPemesanan);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Laporan Transaksi");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setText("Tahun");

        txtTahun.setBackground(new java.awt.Color(255, 255, 255));
        txtTahun.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setText("Bulan");

        cbmBulan.setBackground(new java.awt.Color(255, 255, 255));
        cbmBulan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cbmBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/siminimart/image/search.png"))); // NOI18N

        searchText1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        searchText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchText1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchText1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchText1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbmBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel3)
                    .addComponent(cbmBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemesananMouseClicked
        
       
       
        
      
    }//GEN-LAST:event_tabelPemesananMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String bln = "";
        if (cbmBulan.getSelectedIndex() < 10){
            bln = "0" + cbmBulan.getSelectedIndex();
        } else if (cbmBulan.getSelectedIndex() >= 10){
            bln = "" + cbmBulan.getSelectedIndex();
        }
        
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID Transaksi");
        table.addColumn("Nama");
        table.addColumn("KdBarang");
        table.addColumn("Nama Barang");
        table.addColumn("Jumlah");
        table.addColumn("Total Harga");
        table.addColumn("Tanggal");
        table.addColumn("Status");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi where tgl_transaksi LIKE '%" + txtTahun.getText() + "-"+ bln +"%'";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                });
            }
            tabelPemesanan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
        lebarKolom();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchText1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText1KeyReleased
        String cari = searchText1.getText();
        
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID Transaksi");
        table.addColumn("Nama");
        table.addColumn("KdBarang");
        table.addColumn("Nama Barang");
        table.addColumn("Jumlah");
        table.addColumn("Total Harga");
        table.addColumn("Tanggal");
        table.addColumn("Status");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi where id_transaksi LIKE '%" + cari+ "%' OR nama LIKE '%" + cari+ "%'";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                });
            }
            tabelPemesanan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
        lebarKolom();
    }//GEN-LAST:event_searchText1KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String bln = "";
        if (cbmBulan.getSelectedIndex() < 10){
            bln = "0" + cbmBulan.getSelectedIndex();
        } else if (cbmBulan.getSelectedIndex() >= 10){
            bln = "" + cbmBulan.getSelectedIndex();
        }
        
        File reportFile = new File(".");
        String dirr = "";
        if (txtTahun.getText().equals("")) {
            try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi where tgl_transaksi";
            Statement S = con.createStatement();
            dirr = reportFile.getCanonicalPath() + "/src/admin/siminimart/cetak/";
            JasperDesign design = JRXmlLoader.load(dirr + "CetakLaporan.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = S.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JasperViewer.viewReport(jp);
        } catch (SQLException | IOException ex) {
            JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex, "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } catch (JRException ex) {
            Logger.getLogger(MainLaporan.class.getName()).log(Level.SEVERE, null, ex);
        } 
        } else {
        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi where tgl_transaksi LIKE '%" + txtTahun.getText() + "-"+ bln +"%'";
            Statement S = con.createStatement();
            dirr = reportFile.getCanonicalPath() + "/src/admin/siminimart/cetak/";
            JasperDesign design = JRXmlLoader.load(dirr + "CetakLaporan.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(design);
            ResultSet rs = S.executeQuery(sql);
            JRResultSetDataSource rsDataSource = new JRResultSetDataSource(rs);
            JasperPrint jp = JasperFillManager.fillReport(jr, new HashMap(), rsDataSource);
            JasperViewer.viewReport(jp);
        } catch (SQLException | IOException ex) {
            JOptionPane.showMessageDialog(null, "\nGagal Mencetak\n" + ex, "Kesalahan", JOptionPane.ERROR_MESSAGE);
        } catch (JRException ex) {
            Logger.getLogger(MainLaporan.class.getName()).log(Level.SEVERE, null, ex);
        } 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID Transaksi");
        table.addColumn("Nama");
        table.addColumn("KdBarang");
        table.addColumn("Nama Barang");
        table.addColumn("Jumlah");
        table.addColumn("Total Harga");
        table.addColumn("Tanggal");
        table.addColumn("Status");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi ";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                });
            }
            tabelPemesanan.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
        lebarKolom();
        txtTahun.setText("");
        cbmBulan.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbmBulan;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private admin.siminimart.swing.PanelBorder panelBorder1;
    private admin.siminimart.swing.PanelBorder panelBorder2;
    private admin.siminimart.swing.SearchText searchText1;
    private admin.siminimart.swing.Table tabelPemesanan;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
