/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siminimart.form;


import siminimart.swing.connectionmysql;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import siminimart.component.PanelLoginAndRegister;


/**
 *
 * @author Ahmad Bagus Mas'udi
 */
public class FormTransaksi extends javax.swing.JPanel {
    
    public static String Kode;
    public static String Nama;
    public static String Status;
    public static int TotalHarga;
 
    
    public FormTransaksi() {
        initComponents();
        tampilkanPemesanan();
        lebarKolom();
    }

    public void tampilkanPemesanan() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("ID Transaksi");
        table.addColumn("Nama");
        table.addColumn("KdBarang");
        table.addColumn("Nama Barang");
        table.addColumn("Jumlah");
        table.addColumn("Total Harga");
        table.addColumn("Tanggal");
        table.addColumn("Status");

        try {
            Connection con = connectionmysql.koneksiDB();
            String sql = "select * from transaksi where nama = '"+ PanelLoginAndRegister.Name +"'";
            Statement S = con.createStatement();
            ResultSet R = S.executeQuery(sql);

            while (R.next()) {
                table.addRow(new Object[]{
                    R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                });
            }
            tabelTransaksi.setModel(table);

        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    
    
    public void lebarKolom(){
        TableColumn column;
        tabelTransaksi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabelTransaksi.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = tabelTransaksi.getColumnModel().getColumn(1);
        column.setPreferredWidth(120);
        column = tabelTransaksi.getColumnModel().getColumn(2);
        column.setPreferredWidth(100);
        column = tabelTransaksi.getColumnModel().getColumn(3);
        column.setPreferredWidth(200);
        column = tabelTransaksi.getColumnModel().getColumn(4);
        column.setPreferredWidth(80);
        column = tabelTransaksi.getColumnModel().getColumn(5);
        column.setPreferredWidth(100);
        column = tabelTransaksi.getColumnModel().getColumn(6);
        column.setPreferredWidth(100);
        column = tabelTransaksi.getColumnModel().getColumn(7);
        column.setPreferredWidth(98);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new siminimart.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        panelBorder2 = new siminimart.swing.PanelBorder();
        searchText1 = new siminimart.swing.SearchText();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new siminimart.swing.Table();

        setBackground(new java.awt.Color(242, 242, 242));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Transaksi");

        searchText1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        searchText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText1ActionPerformed(evt);
            }
        });
        searchText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchText1KeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siminimart/image/search.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchText1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchText1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemesananMouseClicked
        
        int baris = tabelTransaksi.rowAtPoint(evt.getPoint());
        
        String kode = tabelTransaksi.getValueAt(baris, 0).toString();
        
        Kode = kode;
        
        String nama = tabelTransaksi.getValueAt(baris, 1).toString().trim();
        Nama = nama;
        
        String totalharga = tabelTransaksi.getValueAt(baris, 5).toString();
        TotalHarga = Integer.parseInt(totalharga);
        
        String status = tabelTransaksi.getValueAt(baris, 6).toString().trim();
        Status = status;
       
        
      
    }//GEN-LAST:event_tabelPemesananMouseClicked

    private void searchText1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchText1KeyReleased
        String cari = searchText1.getText();
        
        try {
            int c = Integer.parseInt(cari);
            DefaultTableModel table = new DefaultTableModel();

            table.addColumn("ID Transaksi");
            table.addColumn("Nama");
            table.addColumn("KdBarang");
            table.addColumn("Nama Barang");
            table.addColumn("Jumlah");
            table.addColumn("Total Harga");
            table.addColumn("Tanggal");
            table.addColumn("Status");

            try {
                Connection con = connectionmysql.koneksiDB();
                String sql = "select * from transaksi where nama = '" + PanelLoginAndRegister.Name + "' && id_transaksi LIKE '%" + cari + "%'";
                Statement S = con.createStatement();
                ResultSet R = S.executeQuery(sql);

                while (R.next()) {
                    table.addRow(new Object[]{
                        R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                    });
                }
                tabelTransaksi.setModel(table);

            } catch (Exception e) {
                e.getMessage();
            }
            lebarKolom();
        } catch (Exception e) {
            DefaultTableModel table = new DefaultTableModel();

            table.addColumn("ID Transaksi");
            table.addColumn("Nama");
            table.addColumn("KdBarang");
            table.addColumn("Nama Barang");
            table.addColumn("Jumlah");
            table.addColumn("Total Harga");
            table.addColumn("Tanggal");
            table.addColumn("Status");

            try {
                Connection con = connectionmysql.koneksiDB();
                String sql = "select * from transaksi where nama = '" + PanelLoginAndRegister.Name + "' && nama_barang LIKE '%" + cari + "%'";
                Statement S = con.createStatement();
                ResultSet R = S.executeQuery(sql);

                while (R.next()) {
                    table.addRow(new Object[]{
                        R.getString(1), R.getString(2), R.getString(3), R.getString(4), R.getString(5), R.getString(6), R.getString(7), R.getString(8)
                    });
                }
                tabelTransaksi.setModel(table);

            } catch (Exception ee) {
                ee.getMessage();
            }
            lebarKolom();

        }
    }//GEN-LAST:event_searchText1KeyReleased

    private void searchText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private siminimart.swing.PanelBorder panelBorder1;
    private siminimart.swing.PanelBorder panelBorder2;
    private siminimart.swing.SearchText searchText1;
    private siminimart.swing.Table tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
