/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siminimart.component;

import siminimart.model.Model_Produk;

/**
 *
 * @author Ahmad Bagus Mas'udi
 */
public class Produk extends javax.swing.JPanel {

    /**
     * Creates new form Produk
     */
    public Produk() {
        initComponents();
        setOpaque(false);
    }
    
    public void setData(Model_Produk data) {
        lbImage.setIcon(data.getImage());
        lbNama.setText(data.getNama());
        lbHarga.setText(data.getHarga());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImage = new javax.swing.JLabel();
        lbNama = new javax.swing.JLabel();
        lbHarga = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siminimart/produk/Ufo Mi Goreng 88G.png"))); // NOI18N
        lbImage.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbNama.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lbNama.setForeground(new java.awt.Color(0, 0, 0));
        lbNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNama.setText("Beras Sumber Jaya");
        lbNama.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbHarga.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbHarga.setForeground(new java.awt.Color(0, 0, 0));
        lbHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHarga.setText("Rp 4.500");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNama, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(lbHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNama)
                .addGap(20, 20, 20)
                .addComponent(lbHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbHarga;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbNama;
    // End of variables declaration//GEN-END:variables
}
